/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as IdeiasRouteImport } from './routes/ideias'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as ProducoesRouteImport } from './routes/producoes'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RoteirosRouteImport } from './routes/roteiros'
import { Route as StoryboardsRouteImport } from './routes/storyboards'
import { Route as ThumbnailsRouteImport } from './routes/thumbnails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeiasRoute = IdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducoesRoute = ProducoesRouteImport.update({
  id: '/producoes',
  path: '/producoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosRoute = RoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardsRoute = StoryboardsRouteImport.update({
  id: '/storyboards',
  path: '/storyboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailsRoute = ThumbnailsRouteImport.update({
  id: '/thumbnails',
  path: '/thumbnails',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fabrica': typeof FabricaRoute
  '/ideias': typeof IdeiasRoute
  '/memoria': typeof MemoriaRoute
  '/producoes': typeof ProducoesRoute
  '/roadmap': typeof RoadmapRoute
  '/roteiros': typeof RoteirosRoute
  '/storyboards': typeof StoryboardsRoute
  '/thumbnails': typeof ThumbnailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fabrica': typeof FabricaRoute
  '/ideias': typeof IdeiasRoute
  '/memoria': typeof MemoriaRoute
  '/producoes': typeof ProducoesRoute
  '/roadmap': typeof RoadmapRoute
  '/roteiros': typeof RoteirosRoute
  '/storyboards': typeof StoryboardsRoute
  '/thumbnails': typeof ThumbnailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fabrica': typeof FabricaRoute
  '/ideias': typeof IdeiasRoute
  '/memoria': typeof MemoriaRoute
  '/producoes': typeof ProducoesRoute
  '/roadmap': typeof RoadmapRoute
  '/roteiros': typeof RoteirosRoute
  '/storyboards': typeof StoryboardsRoute
  '/thumbnails': typeof ThumbnailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/analytics'
    | '/configuracoes'
    | '/fabrica'
    | '/ideias'
    | '/memoria'
    | '/producoes'
    | '/roadmap'
    | '/roteiros'
    | '/storyboards'
    | '/thumbnails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/analytics'
    | '/configuracoes'
    | '/fabrica'
    | '/ideias'
    | '/memoria'
    | '/producoes'
    | '/roadmap'
    | '/roteiros'
    | '/storyboards'
    | '/thumbnails'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/analytics'
    | '/configuracoes'
    | '/fabrica'
    | '/ideias'
    | '/memoria'
    | '/producoes'
    | '/roadmap'
    | '/roteiros'
    | '/storyboards'
    | '/thumbnails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FabricaRoute: typeof FabricaRoute
  IdeiasRoute: typeof IdeiasRoute
  MemoriaRoute: typeof MemoriaRoute
  ProducoesRoute: typeof ProducoesRoute
  RoadmapRoute: typeof RoadmapRoute
  RoteirosRoute: typeof RoteirosRoute
  StoryboardsRoute: typeof StoryboardsRoute
  ThumbnailsRoute: typeof ThumbnailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideias': {
      id: '/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof IdeiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producoes': {
      id: '/producoes'
      path: '/producoes'
      fullPath: '/producoes'
      preLoaderRoute: typeof ProducoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros': {
      id: '/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof RoteirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboards': {
      id: '/storyboards'
      path: '/storyboards'
      fullPath: '/storyboards'
      preLoaderRoute: typeof StoryboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnails': {
      id: '/thumbnails'
      path: '/thumbnails'
      fullPath: '/thumbnails'
      preLoaderRoute: typeof ThumbnailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FabricaRoute: FabricaRoute,
  IdeiasRoute: IdeiasRoute,
  MemoriaRoute: MemoriaRoute,
  ProducoesRoute: ProducoesRoute,
  RoadmapRoute: RoadmapRoute,
  RoteirosRoute: RoteirosRoute,
  StoryboardsRoute: StoryboardsRoute,
  ThumbnailsRoute: ThumbnailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
